# Generated by Django 3.0.8 on 2020-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workflow',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
