# Generated by Django 3.0.8 on 2020-07-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200706_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
